-- Generated by scripts/gen_mysql_ddl.py -- DO NOT EDIT MANUALLY.
-- Baseline revision: 0001_baseline
-- Dialect: mysql

CREATE TABLE med_schema_version (
	revision VARCHAR(32) NOT NULL, 
	applied_at BIGINT NOT NULL, 
	CONSTRAINT pk_med_schema_version PRIMARY KEY (revision)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE TABLE med_session (
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	status VARCHAR(16) NOT NULL DEFAULT 'active', 
	message_count INTEGER NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	updated_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_session PRIMARY KEY (session_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_session_tenant_id_dept_id_status ON med_session (tenant_id, dept_id, status);

CREATE INDEX ix_med_session_updated_at ON med_session (updated_at);

CREATE TABLE med_message_00 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_00 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_00_session_id_created_at ON med_message_00 (session_id, created_at);

CREATE INDEX ix_med_message_00_tenant_id_dept_id ON med_message_00 (tenant_id, dept_id);

CREATE TABLE med_message_01 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_01 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_01_session_id_created_at ON med_message_01 (session_id, created_at);

CREATE INDEX ix_med_message_01_tenant_id_dept_id ON med_message_01 (tenant_id, dept_id);

CREATE TABLE med_message_02 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_02 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_02_session_id_created_at ON med_message_02 (session_id, created_at);

CREATE INDEX ix_med_message_02_tenant_id_dept_id ON med_message_02 (tenant_id, dept_id);

CREATE TABLE med_message_03 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_03 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_03_session_id_created_at ON med_message_03 (session_id, created_at);

CREATE INDEX ix_med_message_03_tenant_id_dept_id ON med_message_03 (tenant_id, dept_id);

CREATE TABLE med_message_04 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_04 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_04_session_id_created_at ON med_message_04 (session_id, created_at);

CREATE INDEX ix_med_message_04_tenant_id_dept_id ON med_message_04 (tenant_id, dept_id);

CREATE TABLE med_message_05 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_05 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_05_session_id_created_at ON med_message_05 (session_id, created_at);

CREATE INDEX ix_med_message_05_tenant_id_dept_id ON med_message_05 (tenant_id, dept_id);

CREATE TABLE med_message_06 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_06 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_06_session_id_created_at ON med_message_06 (session_id, created_at);

CREATE INDEX ix_med_message_06_tenant_id_dept_id ON med_message_06 (tenant_id, dept_id);

CREATE TABLE med_message_07 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_07 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_07_session_id_created_at ON med_message_07 (session_id, created_at);

CREATE INDEX ix_med_message_07_tenant_id_dept_id ON med_message_07 (tenant_id, dept_id);

CREATE TABLE med_message_08 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_08 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_08_session_id_created_at ON med_message_08 (session_id, created_at);

CREATE INDEX ix_med_message_08_tenant_id_dept_id ON med_message_08 (tenant_id, dept_id);

CREATE TABLE med_message_09 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_09 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_09_session_id_created_at ON med_message_09 (session_id, created_at);

CREATE INDEX ix_med_message_09_tenant_id_dept_id ON med_message_09 (tenant_id, dept_id);

CREATE TABLE med_message_10 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_10 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_10_session_id_created_at ON med_message_10 (session_id, created_at);

CREATE INDEX ix_med_message_10_tenant_id_dept_id ON med_message_10 (tenant_id, dept_id);

CREATE TABLE med_message_11 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_11 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_11_session_id_created_at ON med_message_11 (session_id, created_at);

CREATE INDEX ix_med_message_11_tenant_id_dept_id ON med_message_11 (tenant_id, dept_id);

CREATE TABLE med_message_12 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_12 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_12_session_id_created_at ON med_message_12 (session_id, created_at);

CREATE INDEX ix_med_message_12_tenant_id_dept_id ON med_message_12 (tenant_id, dept_id);

CREATE TABLE med_message_13 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_13 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_13_session_id_created_at ON med_message_13 (session_id, created_at);

CREATE INDEX ix_med_message_13_tenant_id_dept_id ON med_message_13 (tenant_id, dept_id);

CREATE TABLE med_message_14 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_14 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_14_session_id_created_at ON med_message_14 (session_id, created_at);

CREATE INDEX ix_med_message_14_tenant_id_dept_id ON med_message_14 (tenant_id, dept_id);

CREATE TABLE med_message_15 (
	message_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	dept_id VARCHAR(64) NOT NULL, 
	patient_id VARCHAR(64) NOT NULL, 
	`role` VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	token_count INTEGER NOT NULL DEFAULT 0, 
	masked BOOL NOT NULL DEFAULT 0, 
	created_at BIGINT NOT NULL, 
	metadata JSON NOT NULL, 
	CONSTRAINT pk_med_message_15 PRIMARY KEY (message_id)
)CHARSET=utf8mb4 ENGINE=InnoDB COLLATE utf8mb4_unicode_ci;

CREATE INDEX ix_med_message_15_session_id_created_at ON med_message_15 (session_id, created_at);

CREATE INDEX ix_med_message_15_tenant_id_dept_id ON med_message_15 (tenant_id, dept_id);
