"""医疗增强 Runnable 层（LCEL 上下文工程）。

当前提供基于存储工厂注入的会话历史增强 Runnable、多租户/科室命名空间隔离所需的
身份上下文与越权守卫、时序滑动窗口裁剪策略、Token 预算裁剪（计数 + 预算内贪心
保留 + 超限告警）、长会话 LLM 摘要压缩（触发阈值 + 摘要写回 system 槽位 +
被折叠区间标记），以及并发会话锁（Redis SETNX 分布式锁 + 看门狗续期 + 本地线程锁
降级）与读写降级（主存储故障 → 备存储兜底 + 每后端一份简易熔断器：失败计数打开、
恢复窗口半开探测、探测成功闭合）；后续迭代将叠加 API 层能力。
"""

from __future__ import annotations

from .fallback import (
    DEFAULT_FAILURE_THRESHOLD,
    DEFAULT_HALF_OPEN_MAX_CALLS,
    DEFAULT_RECOVERY_TIMEOUT_MS,
    DEFAULT_SUCCESS_THRESHOLD,
    CircuitBreaker,
    CircuitBreakerPolicy,
    CircuitSnapshot,
    CircuitState,
    FallbackAttempt,
    FallbackHistory,
    FallbackHistoryResolver,
    FallbackPolicy,
    FallbackReport,
)
from .lock import (
    DEFAULT_ACQUIRE_TIMEOUT_MS,
    DEFAULT_LOCK_TTL_MS,
    DEFAULT_RETRY_INTERVAL_MS,
    LOCK_KEY_PREFIX,
    WATCHDOG_TTL_DIVISOR,
    LocalSessionLock,
    LockPolicy,
    RedisSessionLock,
    SessionLock,
    SessionLockManager,
)
from .med_history_runnable import MedRunnableWithMessageHistory
from .summarizer import (
    COMPRESSED_COUNT_KEY,
    COMPRESSED_RANGE_KEY,
    DEFAULT_SUMMARY_HEADER,
    SUMMARY_FLAG_KEY,
    SUMMARY_INSTRUCTION,
    ExtractiveSummaryChain,
    SummaryChain,
    SummaryCompressor,
    SummaryPolicy,
    SummaryReport,
    SummaryResult,
    build_summary_prompt,
    compressed_count_of,
    compressed_range_of,
    extract_summary_text,
    is_summary_message,
)
from .tenant import (
    NAMESPACE_SEPARATOR,
    STORAGE_KEY_PREFIX,
    SessionNamespace,
    TenantContext,
    TenantGuard,
    build_namespace_key,
    parse_namespace_key,
)
from .token_budget import (
    DEFAULT_TIKTOKEN_ENCODING,
    TIKTOKEN_ENCODINGS,
    TOKEN_COUNT_KEY,
    HeuristicTokenCounter,
    TiktokenTokenCounter,
    TokenBudgetPolicy,
    TokenBudgetTrimmer,
    TokenCounter,
    TokenTrimReport,
    TokenTrimResult,
    message_text,
    resolve_token_counter,
    stored_token_count,
)
from .trimmer import (
    CREATED_AT_KEY,
    ContextWindowPolicy,
    TimeWindowTrimmer,
    extract_created_at,
    find_chief_complaint,
    is_system_message,
    med_role_of,
)

__all__ = [
    "COMPRESSED_COUNT_KEY",
    "COMPRESSED_RANGE_KEY",
    "CREATED_AT_KEY",
    "DEFAULT_ACQUIRE_TIMEOUT_MS",
    "DEFAULT_FAILURE_THRESHOLD",
    "DEFAULT_HALF_OPEN_MAX_CALLS",
    "DEFAULT_LOCK_TTL_MS",
    "DEFAULT_RECOVERY_TIMEOUT_MS",
    "DEFAULT_RETRY_INTERVAL_MS",
    "DEFAULT_SUCCESS_THRESHOLD",
    "DEFAULT_SUMMARY_HEADER",
    "DEFAULT_TIKTOKEN_ENCODING",
    "LOCK_KEY_PREFIX",
    "SUMMARY_FLAG_KEY",
    "SUMMARY_INSTRUCTION",
    "TIKTOKEN_ENCODINGS",
    "TOKEN_COUNT_KEY",
    "WATCHDOG_TTL_DIVISOR",
    "CircuitBreaker",
    "CircuitBreakerPolicy",
    "CircuitSnapshot",
    "CircuitState",
    "ContextWindowPolicy",
    "ExtractiveSummaryChain",
    "FallbackAttempt",
    "FallbackHistory",
    "FallbackHistoryResolver",
    "FallbackPolicy",
    "FallbackReport",
    "HeuristicTokenCounter",
    "LocalSessionLock",
    "LockPolicy",
    "MedRunnableWithMessageHistory",
    "NAMESPACE_SEPARATOR",
    "RedisSessionLock",
    "STORAGE_KEY_PREFIX",
    "SessionLock",
    "SessionLockManager",
    "SessionNamespace",
    "SummaryChain",
    "SummaryCompressor",
    "SummaryPolicy",
    "SummaryReport",
    "SummaryResult",
    "TenantContext",
    "TenantGuard",
    "TiktokenTokenCounter",
    "TimeWindowTrimmer",
    "TokenBudgetPolicy",
    "TokenBudgetTrimmer",
    "TokenCounter",
    "TokenTrimReport",
    "TokenTrimResult",
    "build_namespace_key",
    "build_summary_prompt",
    "compressed_count_of",
    "compressed_range_of",
    "extract_created_at",
    "extract_summary_text",
    "find_chief_complaint",
    "is_summary_message",
    "is_system_message",
    "med_role_of",
    "message_text",
    "parse_namespace_key",
    "resolve_token_counter",
    "stored_token_count",
]
