"""Render the MySQL baseline DDL from the SQLAlchemy schema definition.

The generated script (``migrations/0001_baseline.sql``) is committed to the
repository so DBAs can apply it without installing Python dependencies.

Usage:
    python scripts/gen_mysql_ddl.py [--dialect mysql]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "src"
MIGRATIONS_DIR = ROOT / "migrations"

HEADER = """-- Generated by scripts/gen_mysql_ddl.py -- DO NOT EDIT MANUALLY.
-- Baseline revision: {revision}
-- Dialect: {dialect}
"""


def main() -> int:
    """Render the baseline DDL and write it to ``migrations/``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dialect", default="mysql", help="target SQL dialect (mysql/sqlite)")
    args = parser.parse_args()

    sys.path.insert(0, str(SRC_DIR))
    try:
        from med_langchain_memory.stores.mysql_schema import BASELINE_REVISION, render_ddl
    except ImportError as exc:
        print(f"error: SQLAlchemy is required: {exc}", file=sys.stderr)
        return 1

    ddl = render_ddl(args.dialect)
    MIGRATIONS_DIR.mkdir(parents=True, exist_ok=True)
    target = MIGRATIONS_DIR / f"{BASELINE_REVISION}.sql"
    header = HEADER.format(revision=BASELINE_REVISION, dialect=args.dialect)
    target.write_text(f"{header}\n{ddl}", encoding="utf-8")

    print(f"generated: {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
